### ISSUE TITLE
Strange issue if value showed have the "9" char inside

### ISSUE THREAD

**Issue by webanet** [ClimberAB/ClimberKPI#22]
### Description
it seem that when value have the "9" char, autosize don't work fine and appear "..." symbol
the kpi have same size (2 vertical block, 4 horizontal block).
If you use one more horizontal block, not iussue.

##### Expected behavior

[What you expected to happen]

##### Actual behavior

[What actually happened]

### Versions
KPI latest version 1.5.0, Qliksense Server June 2018
It not depend from the browser used nor to zoom value

### Screenshots
(2 vertical block, 4 horizontal block).
![image](https://user-images.githubusercontent.com/24548879/43918116-781d6e5e-9c12-11e8-96a9-b294987c4d22.png)

(2 vertical block, 5 horizontal block).
![image](https://user-images.githubusercontent.com/24548879/43918395-3e1033bc-9c13-11e8-8d94-b8887bb74e0f.png)

Thanks a lot
Agostino

**Comment by edwardhallgren** [comment]
Hi, Is it possible for you to attach an example application with data showing this problem? Br Edward

**Comment by webanet** [comment]
Try with this.
let me know please
thanks

[TestClimberKPI.zip](https://github.com/ClimberAB/ClimberKPI/files/2278368/TestClimberKPI.zip)

**Comment by Lojdquist** [comment]
Hi,

We would recommend using a different text size.  You can adjust this in the appearance panel, Appearance => Layout =>  Text size. The problem lies in Qliks own font (the font we are using) is not mono-spaced, which means different characters have a different spacing. It's strange Qlik has not implemented this.  Br Axel
